spring.application.name=authentication

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true

# JWT Security Configuration
application.security.jwt.secret-key=NDBFRTYzNTI2NjU1NkE1ODZFMjcyNTc1Mzg3ODJGNDEzRjQ0Mjg0NzJCNEI2MjUwNjQ1MzY3NTY2QjU5NzA=
application.security.jwt.expiration=600000
application.security.jwt.refresh-token.expiration=604800000
